"""
    This module stores constant definitions used across the app.
"""

APP_CONFIG_TOKEN_SLACK_SIGNING_SECRET = 'SLACK_SIGNING_SECRET'
APP_CONFIG_TOKEN_SLACK_BOT_USER_TOKEN = 'SLACK_BOT_USER_TOKEN'
APP_CONFIG_TOKEN_SLACK_USER_TOKEN = 'SLACK_USER_TOKEN'
APP_CONFIG_TOKEN_GITHUB_ACCESS_TOKEN = 'GITHUB_ACCESS_TOKEN'
APP_CONFIG_TOKEN_GITHUB_WEBHOOK_SECRET = 'GITHUB_WEBHOOK_SECRET'
APP_CONFIG_TOKEN_OVH_APP_KEY = 'OVH_APP_KEY'
APP_CONFIG_TOKEN_OVH_APP_SECRET = 'OVH_APP_SECRET'
APP_CONFIG_TOKEN_OVH_CONSUMER_KEY = 'OVH_CONSUMER_KEY'
APP_CONFIG_TOKEN_GODP_AUTH_TOKEN = 'GODP_AUTH_TOKEN'
